# Generated by Django 2.2 on 2019-12-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_test_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('Eng', 'English'), ('Math', 'Maths'), ('Programing', 'Programming'), ('Comp', 'Computer')], default=None, max_length=64),
        ),
    ]
