# Generated by Django 3.0 on 2019-12-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_test_hard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_datastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Eng', 'English'), ('datastruct', 'Datastructure'), ('Programing', 'Programming'), ('Comp', 'Computer')], default=None, max_length=64)),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('answer', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Test_eng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Eng', 'English'), ('datastruct', 'Datastructure'), ('Programing', 'Programming'), ('Comp', 'Computer')], default=None, max_length=64)),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('answer', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Test_hard_datastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Eng', 'English'), ('datastruct', 'Datastructure'), ('Programing', 'Programming'), ('Comp', 'Computer')], default=None, max_length=64)),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('answer', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Test_hard_eng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Eng', 'English'), ('datastruct', 'Datastructure'), ('Programing', 'Programming'), ('Comp', 'Computer')], default=None, max_length=64)),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('answer', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('Eng', 'English'), ('datastruct', 'Datastructure'), ('Programing', 'Programming'), ('Comp', 'Computer')], default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='test_hard',
            name='category',
            field=models.CharField(choices=[('Eng', 'English'), ('datastruct', 'Datastructure'), ('Programing', 'Programming'), ('Comp', 'Computer')], default=None, max_length=64),
        ),
    ]
